[package]
name = "siem_agent"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] } # For HTTP logging (optional)
